// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebForWork.Infrastructure;

#nullable disable

namespace WebForWork.Infrastructure.Migrations
{
    [DbContext(typeof(WebForWorkDbContext))]
    [Migration("20250618132033_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("webforwork")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.ToTable("articles", "webforwork");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("chapters", "webforwork");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("tags", "webforwork");
                });

            modelBuilder.Entity("article_tag", b =>
                {
                    b.Property<Guid>("tagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("articleId")
                        .HasColumnType("uuid");

                    b.HasKey("tagId", "articleId");

                    b.HasIndex("articleId");

                    b.ToTable("article_tag", "webforwork");
                });

            modelBuilder.Entity("chapter_tag", b =>
                {
                    b.Property<Guid>("tagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("chapterId")
                        .HasColumnType("uuid");

                    b.HasKey("tagId", "chapterId");

                    b.HasIndex("chapterId");

                    b.ToTable("chapter_tag", "webforwork");
                });

            modelBuilder.Entity("article_tag", b =>
                {
                    b.HasOne("WebForWork.Domain.Models.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebForWork.Domain.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("chapter_tag", b =>
                {
                    b.HasOne("WebForWork.Domain.Models.Entities.Chapter", null)
                        .WithMany()
                        .HasForeignKey("chapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebForWork.Domain.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
