// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebForWork.Infrastructure;

#nullable disable

namespace WebForWork.Infrastructure.Migrations
{
    [DbContext(typeof(WebForWorkDbContext))]
    partial class WebForWorkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("webforwork")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebForWork.Domain.Models.Aggregates.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.ToTable("articles", "webforwork");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.ArticleTag", b =>
                {
                    b.Property<Guid>("tagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("articleId")
                        .HasColumnType("uuid");

                    b.Property<int>("order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("tagId", "articleId");

                    b.HasIndex("articleId");

                    b.ToTable("articles_tags", "webforwork");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", "webforwork");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.ArticleTag", b =>
                {
                    b.HasOne("WebForWork.Domain.Models.Aggregates.Article", "article")
                        .WithMany("Tags")
                        .HasForeignKey("articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebForWork.Domain.Models.Entities.Tag", "tag")
                        .WithMany("Articles")
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("article");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Aggregates.Article", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WebForWork.Domain.Models.Entities.Tag", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
